In [1]:
import pandas as pd

#Leo el archivo Excel
df = pd.read_excel('C:\\proyectos\\colombia-seguridad-pipeline\\data\\raw\\delitos_2025.xlsx')

#Muestro las primeras 5 filas del DataFrame
print(df.head())

  Unnamed: 0 Unnamed: 1                                         Unnamed: 2  \
0        NaN        NaN  POLICÍA NACIONAL \nDIRECCIÓN DE INVESTIGACIÓN ...
1        NaN        NaN                                                NaN
2        NaN        NaN                                                NaN
3        NaN        NaN                                                NaN
4        NaN        NaN                                                NaN

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0        NaN        NaN        NaN        NaN        NaN        NaN
1        NaN        NaN        NaN        NaN        NaN        NaN
2        NaN        NaN        NaN        NaN        NaN        NaN
3        NaN        NaN        NaN        NaN        NaN        NaN
4        NaN        NaN        NaN        NaN        NaN        NaN

  Unnamed: 9 Unnamed: 10
0        NaN         NaN
1        NaN         NaN
2        NaN         NaN
3        NaN         NaN
4        NaN         NaN

In [ ]:
#Leer primeras 20 filas para inspeccionar el contenido
muestra = pd.read_excel('../data/raw/delitos_2025.xlsx', header=None, nrows=20)
muestra

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,POLICÍA NACIONAL \nDIRECCIÓN DE INVESTIGACIÓN ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ARMAS MEDIOS,DEPARTAMENTO,MUNICIPIO,FECHA HECHO,GENERO,*AGRUPA EDAD PERSONA*,CODIGO DANE,DELITOS,MES,CANTIDAD,ICCS
12,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170,(02011) Agresión (Lesiones personales),01,1,02011
13,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170,(02011) Agresión (Lesiones personales),01,1,02011
14,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170,(02011) Agresión (Lesiones personales),01,1,02011
15,ARMA BLANCA / CORTOPUNZANTE,CESAR,Chiriguaná,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,20178,(02011) Agresión (Lesiones personales),01,1,02011
16,CONTUNDENTES,NORTE DE SANTANDER,Cúcuta,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,54001,(02011) Agresión (Lesiones personales),01,1,02011
17,ARMA DE FUEGO,NORTE DE SANTANDER,Cúcuta,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,54001,(02011) Agresión (Lesiones personales),01,1,02011
18,ARMA DE FUEGO,CESAR,Agustín Codazzi,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,20013,(02011) Agresión (Lesiones personales),01,1,02011
19,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170,(02011) Agresión (Lesiones personales),01,1,02011

In [ ]:
# Leo el archivo Excel con la fila 11 como encabezado, ya que las primeras filas contienen información no relevante
df = pd.read_excel('../data/raw/delitos_2025.xlsx', header=11)
df.head()

,ARMAS MEDIOS,DEPARTAMENTO,MUNICIPIO,FECHA HECHO,GENERO,*AGRUPA EDAD PERSONA*,CODIGO DANE,DELITOS,MES,CANTIDAD,ICCS
0,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170.0,(02011) Agresión (Lesiones personales),1.0,1.0,2011.0
1,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170.0,(02011) Agresión (Lesiones personales),1.0,1.0,2011.0
2,ARMA DE FUEGO,RISARALDA,Dosquebradas,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,66170.0,(02011) Agresión (Lesiones personales),1.0,1.0,2011.0
3,ARMA BLANCA / CORTOPUNZANTE,CESAR,Chiriguaná,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,20178.0,(02011) Agresión (Lesiones personales),1.0,1.0,2011.0
4,CONTUNDENTES,NORTE DE SANTANDER,Cúcuta,2025/01/01,MASCULINO,DE 18 AÑOS Y MÁS,54001.0,(02011) Agresión (Lesiones personales),1.0,1.0,2011.0

In [ ]:
# Verificar la forma del DataFrame para conocer si hay filas que no contienen datos relevantes
df.shape

(773961, 11)

In [ ]:
# Verificar los tipos de datos de cada columna para identificar posibles problemas de conversión
df.dtypes

ARMAS MEDIOS                 str
DEPARTAMENTO                 str
MUNICIPIO                    str
FECHA HECHO                  str
GENERO                       str
*AGRUPA EDAD PERSONA*        str
CODIGO DANE              float64
DELITOS                      str
MES                      float64
CANTIDAD                 float64
ICCS                     float64
dtype: object

In [14]:
df.tail(20)

,ARMAS MEDIOS,DEPARTAMENTO,MUNICIPIO,FECHA HECHO,GENERO,*AGRUPA EDAD PERSONA*,CODIGO DANE,DELITOS,MES,CANTIDAD,ICCS
773941,ARMA DE FUEGO,ANTIOQUIA,Medellín,2025/05/25,MASCULINO,DE 18 AÑOS Y MÁS,5001.0,(050212) Hurto a motocicletas,5.0,1.0,50212.0
773942,SIN EMPLEO DE ARMAS,META,Villavicencio,2025/12/02,MASCULINO,DE 18 AÑOS Y MÁS,50001.0,(050212) Hurto a motocicletas,12.0,1.0,50212.0
773943,SIN EMPLEO DE ARMAS,VALLE,Cali,2025/11/16,MASCULINO,DE 18 AÑOS Y MÁS,76001.0,(050211) Hurto a automotores,11.0,1.0,50211.0
773944,SIN EMPLEO DE ARMAS,ANTIOQUIA,Medellín,2025/11/27,FEMENINO,DE 18 AÑOS Y MÁS,5001.0,(050212) Hurto a motocicletas,11.0,1.0,50212.0
773945,LLAVE MAESTRA,VALLE,Cali,2025/12/02,FEMENINO,DE 18 AÑOS Y MÁS,76001.0,(050212) Hurto a motocicletas,12.0,1.0,50212.0
773946,SIN EMPLEO DE ARMAS,ANTIOQUIA,Medellín,2025/04/25,MASCULINO,DE 18 AÑOS Y MÁS,5001.0,(050212) Hurto a motocicletas,4.0,1.0,50212.0
773947,LLAVE MAESTRA,VALLE,Cali,2025/11/01,MASCULINO,DE 18 AÑOS Y MÁS,76001.0,(050212) Hurto a motocicletas,11.0,1.0,50212.0
773948,SIN EMPLEO DE ARMAS,VALLE,Cali,2025/11/26,MASCULINO,DE 18 AÑOS Y MÁS,76001.0,(050212) Hurto a motocicletas,11.0,1.0,50212.0
773949,LLAVE MAESTRA,VALLE,Cali,2025/11/29,MASCULINO,DE 18 AÑOS Y MÁS,76001.0,(050212) Hurto a motocicletas,11.0,1.0,50212.0
773950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773951,Fuente: POLICÍA NACIONAL - Estadísticas de del...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773952,Fecha de entrega: 20 de agosto de 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773953,Nota: Esta información corresponde a los archi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773960,Nota: ICCS (International Classification of Cr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
ruta = '../data/raw/delitos_2025.xlsx'

df = pd.read_excel(
    ruta,
    header=11,
    dtype={'MES': str, 'CODIGO DANE': str, 'ICCS': str},
)
df.shape

(773961, 11)

In [16]:
notas = df.iloc[773950:, 0].dropna().tolist()
for nota in notas:
    print(nota)
    print('---')

Fuente: POLICÍA NACIONAL - Estadísticas de delitos contra la seguridad y convivencia ciudadana, así como de la actividad operativa registrada por la Policía Nacional
---
Fecha de entrega: 20 de agosto de 2026
---
Nota: Esta información corresponde a los archivos que se venían publicando como reportes de la operación estadística, sin embargo, las variables de género y edad etarea no cuentan con la calidad en cuanto a completitud, ya que se encuentran en un proceso de calidad y consistencia de la información.

En consecuencia, se recomienda a los usuarios consultar la sección "CUADROS DE SALIDA DELICTIVO", correspondiente al nuevo set de 12 cuadros con información validada correctamente para los 18 delitos de convivencia y seguridad ciudadana, según los lineamientos del DANE y el cual permiten la replicabilidad de los mismos.
---
Nota: ICCS (International Classification of Crime for Statistical Purposes) Es la Clasificación Internacional del Delito con fines estadísticos adaptada para Colombia del DANE - 2022.
---

In [17]:
df = df.dropna(subset=['DEPARTAMENTO'])
df.shape

(773950, 11)

In [18]:
print(df.dtypes)
df[df['MUNICIPIO'] == 'Medellín'][['MUNICIPIO', 'CODIGO DANE', 'MES', 'ICCS']].tail()

ARMAS MEDIOS                 str
DEPARTAMENTO                 str
MUNICIPIO                    str
FECHA HECHO                  str
GENERO                       str
*AGRUPA EDAD PERSONA*        str
CODIGO DANE                  str
DELITOS                      str
MES                          str
CANTIDAD                 float64
ICCS                         str
dtype: object

       MUNICIPIO CODIGO DANE MES    ICCS
773928  Medellín       05001  11  050212
773929  Medellín       05001  12  050212
773941  Medellín       05001  05  050212
773944  Medellín       05001  11  050212
773946  Medellín       05001  04  050212

In [20]:
columnas_codigo = {'MES': str, 'CODIGO DANE': str, 'ICCS': str}

df.to_csv('../data/interim/delitos_2025.csv', index=False, encoding='utf-8-sig')

In [21]:
prueba = pd.read_csv('../data/interim/delitos_2025.csv', dtype=columnas_codigo)
print(prueba.shape)
prueba['CODIGO DANE'].head(3)

(773950, 11)

0    66170
1    66170
2    66170
Name: CODIGO DANE, dtype: str

In [22]:
df.isna().sum()

ARMAS MEDIOS                 0
DEPARTAMENTO                 0
MUNICIPIO                    7
FECHA HECHO                  0
GENERO                   30296
*AGRUPA EDAD PERSONA*     4160
CODIGO DANE                  0
DELITOS                      0
MES                          0
CANTIDAD                     0
ICCS                         0
dtype: int64

In [23]:
for columna in ['ARMAS MEDIOS', 'GENERO', '*AGRUPA EDAD PERSONA*']:
    print(columna)
    print(df[columna].value_counts(dropna=False))
    print()

ARMAS MEDIOS
ARMAS MEDIOS
SIN EMPLEO DE ARMAS                   524466
ARMA DE FUEGO                          73234
CONTUNDENTES                           63580
ARMA BLANCA / CORTOPUNZANTE            59409
NO REPORTADO                           15727
LLAVE MAESTRA                           8897
LLAMADA TELEFONICA                      6909
VEHICULO                                5455
PALANCAS                                4556
MOTO                                    2989
ESCOPOLAMINA                            2345
DIRECTA                                 2208
REDES SOCIALES                          2148
CARTA EXTORSIVA                          568
ARTEFACTO EXPLOSIVO/CARGA DINAMITA       462
ARMA TRAUMATICA                          403
DRON / EXPLOSIVO                         124
MIXTA                                     71
GRANADA DE MANO                           62
PERRO                                     53
BICICLETA                                 52
COMBUSTIBLE                               50
CARRO BOMBA                               35
GASES                                     18
ACIDO                                     16
QUIMICOS                                  11
POLVORA(FUEGOS PIROTECNICOS)              11
CINTAS/CINTURON                           11
MINA ANTIPERSONA                          11
PAQUETE BOMBA                             11
MOTO BOMBA                                11
SUSTANCIAS TOXICAS                         9
AGUA CALIENTE                              6
JERINGA                                    5
ARTEFACTO INCENDIARIO                      5
MEDICAMENTOS                               4
ALIMENTOS VENCIDOS                         4
CILINDRO BOMBA                             4
PETARDO PLANFETARIO                        3
VENENO                                     2
LICOR ADULTERADO                           1
ESPOSAS                                    1
BICICLETA BOMBA                            1
GRANADA DE FUSIL                           1
GRANADA DE MORTERO                         1
Name: count, dtype: int64

GENERO
GENERO
MASCULINO    391578
FEMENINO     352076
NaN           30296
Name: count, dtype: int64

*AGRUPA EDAD PERSONA*
*AGRUPA EDAD PERSONA*
DE 18 AÑOS Y MÁS    732877
DE 14 A 17 AÑOS      22064
DE 0 A 14 AÑOS       14849
NaN                   4160
Name: count, dtype: int64

In [26]:
print(df['DELITOS'].nunique())
print('Departamentos:', df['DEPARTAMENTO'].nunique())
print('Municipios (por nombre):', df['MUNICIPIO'].nunique())
print('Municipios (por código DANE):', df['CODIGO DANE'].nunique())

18
Departamentos: 33
Municipios (por nombre): 1020
Municipios (por código DANE): 1110

In [25]:
df['DELITOS'].value_counts()

DELITOS
(05022) Hurto a personas                                                                        289374
(02089) Otros actos dirigidos a inducir miedo o angustia emocional (Violencia intrafamiliar)    138805
(02011) Agresión (Lesiones personales)                                                           86398
(02019) Otras formas de agresiones y amenazas (Lesiones culposas en accidentes de tránsito)      48432
(02012) Amenaza                                                                                  44904
(050212) Hurto a motocicletas                                                                    34625
(0301) Violación (Delitos sexuales)                                                              32985
(05023) Hurto a comercio                                                                         26331
(05010) Hurto a residencias                                                                      25813
(0101) Homicidio intencional                                                                     14037
(02051) Extorsión                                                                                13441
(050211) Hurto a automotores                                                                      9397
(10321) Homicidio por tránsito vehicular (Homicidios en accidentes de tránsito)                   7560
(05024) Abigeato (Hurto a cabezas de ganado)                                                       813
(020222) Retención ilegal (Secuestro)                                                              702
(0906) Terrorismo                                                                                  189
(05040) Hurto de objetos de valor o bienes en tránsito (Hurto pirateria terrestre)                 101
(05030) Hurto a entidades financieras                                                               43
Name: count, dtype: int64

In [27]:
fechas = pd.to_datetime(df['FECHA HECHO'])
print('Primera:', fechas.min())
print('Última:', fechas.max())
print('Fechas no válidas:', fechas.isna().sum())

Primera: 2025-01-01 00:00:00
Última: 2025-12-31 00:00:00
Fechas no válidas: 0

In [30]:
df.groupby('MUNICIPIO')['CODIGO DANE'].nunique().sort_values(ascending=False).head(10)

MUNICIPIO
Leticia       7
La Unión      4
Buenavista    4
Villanueva    4
El Peñón      3
Granada       3
Guadalupe     3
Albania       3
Córdoba       3
Argelia       3
Name: CODIGO DANE, dtype: int64

In [32]:
df.groupby(['DEPARTAMENTO', 'MUNICIPIO'])['CODIGO DANE'].nunique().sort_values(ascending=False).head(50)

DEPARTAMENTO  MUNICIPIO
AMAZONAS      Leticia                 7
GUAINÍA       Inírida                 2
ANTIOQUIA     Abejorral               1
              Abriaquí                1
              Alejandría              1
              Amagá                   1
              Amalfi                  1
              Andes                   1
              Angelópolis             1
              Angostura               1
              Anorí                   1
              Anza                    1
              Apartadó                1
              Arboletes               1
              Argelia                 1
VALLE         Trujillo                1
              Tuluá                   1
              Ulloa                   1
              Versalles               1
              Vijes                   1
              Yotoco                  1
              Yumbo                   1
              Zarzal                  1
VAUPÉS        Caruru                  1
              Mitú                    1
              Taraira                 1
VICHADA       Cumaribo                1
              La Primavera            1
              Puerto Carreño          1
ANTIOQUIA     Carolina                1
              Caucasia                1
              Cañasgordas             1
              Chigorodó               1
              Cisneros                1
              Ciudad Bolívar          1
              Cocorná                 1
              Concepción              1
              Concordia               1
              Copacabana              1
              Cáceres                 1
              Dabeiba                 1
              Don Matías              1
              Ebéjico                 1
              El Bagre                1
              El Carmen de Viboral    1
              El Santuario            1
              Entrerrios              1
              Envigado                1
              Fredonia                1
              Frontino                1
Name: CODIGO DANE, dtype: int64